### ISSUE TITLE
[Suggestion] Add creative crafter upgrade

### ISSUE THREAD

**Issue by DeleteMetaInf** [starforcraft/Creative-Crafter#10]
When you have a lot of ordinary crafters or iron/gold/diamond/Netherite crafters (from [ExtraStorage](https://www.curseforge.com/minecraft/mc-mods/extrastorage)) sitting around, it can be a pain to upgrade them to creative crafters, as you have to break them, reorientate them, and put all the patterns back in, which can take a while, especially if you have the aforementioned crafters from Extra Storage, which add more pattern slots, and it also ruins the orginization of the patterns unless you take each one out manually before breaking the crafter.

I think it’d be fantastic if you could add an upgrade item, with which you can right-click on any crafter (including ExtraStorage crafters) to upgrade them to creative crafters. That’d save you the hassle of having to break them, reorientate them, and put all the patterns back into it.

**Comment by starforcraft** [comment]
Unfortunately as far as I know this isn’t possible

**Comment by DeleteMetaInf** [comment]
Oh, that’s a shame. 😕
