### ISSUE TITLE
Crashing with last version 1.19.2

### ISSUE THREAD

**Issue by Jly4** [starforcraft/Creative-Crafter#13]
Minecraft crashes when I add a last version creative crafter 1.19.2

Logs with creativecrafter-1.19.2-0.31 - Normal loading  - https://mclo.gs/ibbJkAV
Logs with creativecrafter-1.19.2-1.0 - Crashing - https://mclo.gs/ZlyjWfe

Minecraft: 1.19.2
Forge: 43.2.3

**Comment by Jly4** [comment]
hmm, apparently this is a problem on the part of [ae2wtlib](https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/163)

**Comment by starforcraft** [comment]
Huh this is really weird.. Both mods do nothing against each other

**Comment by starforcraft** [comment]
Thanks for the report! I will still try fixing it

**Comment by Jly4** [comment]
Did you follow my link? This is a common problem with the ae2wtlib mod. Apparently the problem is not on your side.

> Thanks for the report! I will still try fixing it

**Comment by starforcraft** [comment]
Yeah I clicked on it, but perhaps there could be a workaround

**Comment by starforcraft** [comment]
There isn't one
