### ISSUE TITLE
Creative crafter removes redstone controls for crafters added by Extra Storage (and removes redstone control for itself as well)

### ISSUE THREAD

**Issue by Artcore1992** [starforcraft/Creative-Crafter#14]
Hi, 

I'm currently running ATM8 server with Extra Storage mod included, when adding in Creative Crafter (running creativecrafter-1.19.2-0.31.jar - because as stated in another issue - newer one crashes the server) the redstone controls for Crafters (all of them except basic RS crafter) disappear. Tested in Single player by removing Creative Crafter - redstone controls were back.

**Comment by starforcraft** [comment]
Caused by https://github.com/starforcraft/Creative-Crafter/issues/13 and https://github.com/refinedmods/refinedstorage/issues/3449
