### ISSUE TITLE
Lightspeed Crafter removes all recipes

### ISSUE THREAD

**Issue by Shoki17** [starforcraft/Creative-Crafter#16]
I play on TNP Limitless 6 and after about 4 days of having my Lightspeed Crafter setup with multiple recipes, they have all now vanished when logging in today. There was an issue with the Netherite Crafter from Extra Storage mod that had the same issue, so I'm not sure if it's relateable. 

Any thoughts on the issue or possibly another mod that could be interfering that needs to be removed?

Server has 12 hour interval restarts as well.

Steps to reproduce:
1. Place Lightspeed Crafter with Refined Storage setup
2. Wait a few days for the recipes to be removed
3. File the issue and wait for feedback

**Comment by starforcraft** [comment]
Lightspeed Crafter?

**Comment by Shoki17** [comment]
> Lightspeed Crafter?

Yes, that is what it's called. Or is this the wrong mod? The nbt tag shows that Creative Crafter is the proper mod for the Lightspeed Crafter.

![Screenshot 2023-09-30 120000](https://github.com/starforcraft/Creative-Crafter/assets/111270243/9e4eb4cc-912e-4089-b796-e6877419e712)

**Comment by jinkhya** [comment]
Hello, had the same issue on our server for one of our players on TNP Limitless 7. I had a look at server logs around the time it happened and there might be something about it line 41151 in the log file below, which involves fastsuite. Is that ConcurrentModificationException related?

https://gist.github.com/jinkhya/1965b09e37914a627b0a4d27381414ac

**Comment by starforcraft** [comment]
Should be fixed now in 1.20.1 (A fix for1.19.2 depends on if RS backports this change https://github.com/refinedmods/refinedstorage/commit/9b30bece19c0e2cd843921b2cbe7f2ca9d347def)
